
//! Autogenerated weights for swork
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 2.0.0
//! DATE: 2021-01-25, STEPS: [], REPEAT: 20, LOW RANGE: [], HIGH RANGE: []
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// ../target/release/crust
// benchmark
// --execution
// wasm
// --pallet
// swork
// --extrinsic
// *
// --repeat
// 20
// --wasm-execution
// compiled
// --output
// ../cstrml/swork/src/weight.rs


#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for swork.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	fn upgrade() -> Weight {
		(43_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	fn register() -> Weight {
		(4_801_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn report_works(added: u32, deleted: u32) -> Weight {
		(3_105_000_000 as Weight)
			.saturating_add((515_000_000 as Weight).saturating_mul(added as Weight))
			.saturating_add((287_000_000 as Weight).saturating_mul(deleted as Weight))
			.saturating_add(T::DbWeight::get().reads(1 as Weight).saturating_mul(added as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight).saturating_mul(added as Weight))
			.saturating_add(T::DbWeight::get().reads(3 as Weight).saturating_mul(deleted as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight).saturating_mul(deleted as Weight))
	}
	fn create_group() -> Weight {
		(58_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(6 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	fn join_group() -> Weight {
		(123_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	fn quit_group() -> Weight {
		(123_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	fn kick_out() -> Weight {
		(123_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(7 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
}
