[package]
authors = ["Brian Smith <brian@briansmith.org>"]
name = "pregenerate_asm"
version = "0.0.1"

[[bin]]
name = "pregenerate_asm"
path = "../build.rs"

# Keep this in sync with `[build-dependencies]` in ../Cargo.toml.
[dependencies]
cc = "1.0.26"
which = { version = "3.1.1" }
