name: Crust MainNet Upgrade Checker

on:
  pull_request:
    branches:
      - mainnet
    types: [created, edited]

jobs:
  mainnet_upgrade_checker:
    runs-on: ubuntu-latest
    name: MainNet Upgrade Checker
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: CheckList
        uses: allthatjazzleo/actions-pull-request-add-comment@v1
        if: >-
          github.event_name == 'pull_request' && github.event.pull_request.title == '[Runtime] MainNet Upgrade'
        with:
          message: '**This checklist should applied every bump version on `mainnet` branch**
          <br/>1. Spec version
          <br/>2. List the features of PRs in this upgrade
          <br/>3. Has types change? (Will this affect API/sManager/Subscan/Other Services)
          <br/>4. Need do the storage migration?
          <br/>5. Has interface change?(Extrinsic/Chain state/Event changed)
          <br/>6. Make sure the WASM building env
          <br/>7. Need announcements?
          <br/>8. Need initial actions? (like setXXXPot/setFlags/...)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
