name: Crust MainNet Upgrade Checker

on:
  pull_request:
    branches:
      - mainnet
    types: [created, edited]

jobs:
  mainnet_upgrade_checker:
    runs-on: ubuntu-latest
    name: MainNet Upgrade Checker
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: CheckList
        uses: allthatjazzleo/actions-pull-request-add-comment@v1
        if: >-
          github.event_name == 'pull_request' && github.event.pull_request.title == '[Runtime] MainNet Upgrade'
        with:
          message: 'This checklist should applied every bump version on `mainnet` branch
          <br/>- [ ] Feature in PRs
          <br/>- [ ] Types change (Will this affect API/sManager/Subscan/Other Services)
          <br/>- [ ] Storage migration
          <br/>- [ ] Interface changed(Extrinsic/Chain state/Event changed)
          <br/>- [ ] WASM building env
          <br/>- [ ] Announcement'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
